### ISSUE TITLE
Etiborlilik

### ISSUE THREAD

**Issue by mrshuhrat** [ajasurbek/js_lesson-5#2]
Vergullardan oldin bosh joy qolmagani maqulroq.
![image](https://user-images.githubusercontent.com/68459940/98568568-0e66e400-22d3-11eb-8ab8-5281aaf349b5.png)

**Comment by Muhammadjewel** [comment]
```
elForma.addEventListener('submit' , fn () {});

elForma.addEventListener('submit', fn () {});
```
